name: go-server-aws-deploy-demo
on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout responsitory
        uses: actions/checkout@v3

      - name: Go Setup
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'

      - name: Check go version
        run: go version